Fix failing Github tests (#726)
Summary:
Pull Request resolved: https://github.com/pytorch/opacus/pull/726

(1) CIFAR10 cuda tests were failing with the following message. [Example](https://github.com/pytorch/opacus/actions/runs/13079011269/job/36498002040#step:7:757).

> _pickle.UnpicklingError: Weights only load failed [...] In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.

Specified weights_only=False in torch.load() and tests are passing.

(2) A similar issue was happening with multiple unit tests due to the change in behavior of `weights_only`. [Example](https://github.com/pytorch/opacus/actions/runs/13080274224/job/36502044189). Changed the `weights_only` setting where necessary.

(3) Black was requesting addition of commas when listing mutliple variable types. (Locally there were no issues, appeared only GithubActions). [Example](https://github.com/pytorch/opacus/actions/runs/13080274224/job/36502043210).

Reviewed By: EnayatUllah

Differential Revision: D68973109

fbshipit-source-id: 7fbe9702dcfc72b40fe95bb8a749d2163525231b